#!/usr/bin/env bash
#
# Builds the speech-to-text assets behind live subtitles:
#   1. subtitles-worker.<hash>.js — parakeet.js + its onnxruntime-web (1.24.1)
#      bundled into a classic Worker script (esbuild)
#   2. vad.<hash>.js — @ricky0123/vad-web (Silero VAD) + onnxruntime-web
#      bundled as an ES module, dynamic-import()ed on the main thread
#   3. The onnxruntime runtime pair + the VAD model/worklet, in a
#      version-stamped directory. The ort module glue ships under a .js name:
#      nginx serves .mjs as application/octet-stream, which module imports
#      hard-reject, so nothing user-facing may carry a .mjs extension.
#
# Model weights (~2.5GB) are NOT built or committed: they come from
# HuggingFace at runtime (or a resenha_stt_model_base_url mirror).
#
# Versions are pinned via package.json devDependencies (parakeet.js,
# @ricky0123/vad-web). Commit public/javascripts/stt/ and the regenerated
# assets/javascripts/discourse/lib/resenha/stt-assets.js.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT_DIR="${PLUGIN_DIR}/public/javascripts/stt"
MANIFEST="${PLUGIN_DIR}/assets/javascripts/discourse/lib/resenha/stt-assets.js"
PUBLIC_BASE="/plugins/resenha/javascripts/stt"

hash8() {
  sha256sum "$1" | cut -c1-8
}

cd "${PLUGIN_DIR}"
pnpm install --silent

pkg_version() {
  node -p "JSON.parse(require('fs').readFileSync('node_modules/$1/package.json')).version"
}

PARAKEET_ORT_VERSION="$(pkg_version onnxruntime-web)"
VAD_VERSION="$(pkg_version "@ricky0123/vad-web")"
VAD_ORT_VERSION="$(pkg_version "@ricky0123/vad-web/node_modules/onnxruntime-web" 2>/dev/null || pkg_version onnxruntime-web)"

echo "==> Step 1: Bundle the transcription worker (parakeet.js + ort ${PARAKEET_ORT_VERSION})"

WORKER_TMP="$(mktemp --suffix=.js)"
VAD_TMP="$(mktemp --suffix=.vad.js)"
trap 'rm -f "${WORKER_TMP}" "${VAD_TMP}"' EXIT

pnpm exec esbuild "${PLUGIN_DIR}/src/stt-worker/worker.js" \
  --bundle --format=iife --minify --outfile="${WORKER_TMP}"

echo "==> Step 2: Bundle the VAD module (@ricky0123/vad-web ${VAD_VERSION})"

pnpm exec esbuild "${PLUGIN_DIR}/src/stt-worker/vad-entry.js" \
  --bundle --format=esm --minify --outfile="${VAD_TMP}"

echo "==> Step 3: Emit assets + manifest"

if [ "${VAD_ORT_VERSION}" != "${PARAKEET_ORT_VERSION}" ]; then
  echo "ERROR: vad-web resolved onnxruntime-web ${VAD_ORT_VERSION}, expected ${PARAKEET_ORT_VERSION}." >&2
  echo "       Both bundles must share one runtime dir; align the pins." >&2
  exit 1
fi

rm -rf "${OUTPUT_DIR}"
ORT_DIR="ort-${PARAKEET_ORT_VERSION}"
VAD_DIR="vad-${VAD_VERSION}"
mkdir -p "${OUTPUT_DIR}/${ORT_DIR}" "${OUTPUT_DIR}/${VAD_DIR}"

WORKER_NAME="subtitles-worker.$(hash8 "${WORKER_TMP}").js"
VAD_BUNDLE_NAME="vad.$(hash8 "${VAD_TMP}").js"
install -m 644 "${WORKER_TMP}" "${OUTPUT_DIR}/${WORKER_NAME}"
install -m 644 "${VAD_TMP}" "${OUTPUT_DIR}/${VAD_BUNDLE_NAME}"

# One runtime pair serves both consumers via explicit {mjs, wasm} URLs; the
# jsep build is a superset (wasm + webgpu execution providers).
install -m 644 node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.jsep.wasm \
  "${OUTPUT_DIR}/${ORT_DIR}/ort-wasm-simd-threaded.jsep.wasm"
install -m 644 node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.jsep.mjs \
  "${OUTPUT_DIR}/${ORT_DIR}/ort-wasm-simd-threaded.jsep.js"

install -m 644 node_modules/@ricky0123/vad-web/dist/silero_vad_v5.onnx \
  node_modules/@ricky0123/vad-web/dist/silero_vad_legacy.onnx \
  node_modules/@ricky0123/vad-web/dist/vad.worklet.bundle.min.js \
  "${OUTPUT_DIR}/${VAD_DIR}/"

cat > "${MANIFEST}" <<EOF
// Generated by scripts/build-stt-assets.sh — do not edit.
export const STT_WORKER_PATH = "${PUBLIC_BASE}/${WORKER_NAME}";
export const VAD_BUNDLE_PATH = "${PUBLIC_BASE}/${VAD_BUNDLE_NAME}";
export const ORT_WASM_JS = "${PUBLIC_BASE}/${ORT_DIR}/ort-wasm-simd-threaded.jsep.js";
export const ORT_WASM_BINARY = "${PUBLIC_BASE}/${ORT_DIR}/ort-wasm-simd-threaded.jsep.wasm";
export const VAD_ASSET_BASE = "${PUBLIC_BASE}/${VAD_DIR}/";
EOF

pnpm exec prettier --write --log-level silent "${MANIFEST}"

echo "==> Build complete!"
ls -la "${OUTPUT_DIR}"
echo "    ${MANIFEST}"
