#!/usr/bin/env bash
#
# Builds the speech-to-text assets behind live subtitles:
#   1. subtitles-worker.<hash>.js — parakeet.js + its onnxruntime-web (1.24.1)
#      bundled into a classic Worker script (esbuild)
#   2. vad.<hash>.mjs — @ricky0123/vad-web (Silero VAD) + its onnxruntime-web
#      (1.27.x) bundled as an ES module, dynamic-import()ed on the main thread
#   3. The two onnxruntime WASM runtimes + the VAD model/worklet, copied into
#      version-stamped directories (ort resolves its .wasm files by canonical
#      name inside a base dir, so those names can't be hashed — the version
#      in the path is the cache-buster)
#
# Model weights (~2.5GB) are NOT built or committed: they come from
# HuggingFace at runtime (or a resenha_stt_model_base_url mirror).
#
# Versions are pinned via package.json devDependencies (parakeet.js,
# @ricky0123/vad-web). Commit public/javascripts/stt/ and the regenerated
# assets/javascripts/discourse/lib/resenha/stt-assets.js.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT_DIR="${PLUGIN_DIR}/public/javascripts/stt"
MANIFEST="${PLUGIN_DIR}/assets/javascripts/discourse/lib/resenha/stt-assets.js"
PUBLIC_BASE="/plugins/resenha/javascripts/stt"

hash8() {
  sha256sum "$1" | cut -c1-8
}

cd "${PLUGIN_DIR}"
pnpm install --silent

pkg_version() {
  node -p "JSON.parse(require('fs').readFileSync('node_modules/$1/package.json')).version"
}

PARAKEET_ORT_VERSION="$(pkg_version onnxruntime-web)"
VAD_VERSION="$(pkg_version "@ricky0123/vad-web")"
VAD_ORT_VERSION="$(pkg_version "@ricky0123/vad-web/node_modules/onnxruntime-web" 2>/dev/null || pkg_version onnxruntime-web)"

echo "==> Step 1: Bundle the transcription worker (parakeet.js + ort ${PARAKEET_ORT_VERSION})"

WORKER_TMP="$(mktemp --suffix=.js)"
VAD_TMP="$(mktemp --suffix=.mjs)"
trap 'rm -f "${WORKER_TMP}" "${VAD_TMP}"' EXIT

pnpm exec esbuild "${PLUGIN_DIR}/src/stt-worker/worker.js" \
  --bundle --format=iife --minify --outfile="${WORKER_TMP}"

echo "==> Step 2: Bundle the VAD module (@ricky0123/vad-web ${VAD_VERSION})"

pnpm exec esbuild "${PLUGIN_DIR}/src/stt-worker/vad-entry.js" \
  --bundle --format=esm --minify --outfile="${VAD_TMP}"

echo "==> Step 3: Emit assets + manifest"

rm -rf "${OUTPUT_DIR}"
ORT_DIR="ort-${PARAKEET_ORT_VERSION}"
VAD_DIR="vad-${VAD_VERSION}"
if [ "${VAD_ORT_VERSION}" = "${PARAKEET_ORT_VERSION}" ]; then
  VAD_ORT_DIR="${ORT_DIR}"
else
  VAD_ORT_DIR="vad-ort-${VAD_ORT_VERSION}"
fi
mkdir -p "${OUTPUT_DIR}/${ORT_DIR}" "${OUTPUT_DIR}/${VAD_DIR}" "${OUTPUT_DIR}/${VAD_ORT_DIR}"

WORKER_NAME="subtitles-worker.$(hash8 "${WORKER_TMP}").js"
VAD_BUNDLE_NAME="vad.$(hash8 "${VAD_TMP}").mjs"
install -m 644 "${WORKER_TMP}" "${OUTPUT_DIR}/${WORKER_NAME}"
install -m 644 "${VAD_TMP}" "${OUTPUT_DIR}/${VAD_BUNDLE_NAME}"

# The worker's ort needs the WebGPU (jsep) wasm artifacts.
install -m 644 node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.jsep.wasm \
  node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.jsep.mjs \
  node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.wasm \
  node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.mjs \
  "${OUTPUT_DIR}/${ORT_DIR}/"

# The VAD's ort only runs plain wasm.
VAD_ORT_DIST="node_modules/@ricky0123/vad-web/node_modules/onnxruntime-web/dist"
[ -d "${VAD_ORT_DIST}" ] || VAD_ORT_DIST="node_modules/onnxruntime-web/dist"
install -m 644 "${VAD_ORT_DIST}/ort-wasm-simd-threaded.wasm" \
  "${VAD_ORT_DIST}/ort-wasm-simd-threaded.mjs" \
  "${OUTPUT_DIR}/${VAD_ORT_DIR}/"

install -m 644 node_modules/@ricky0123/vad-web/dist/silero_vad_v5.onnx \
  node_modules/@ricky0123/vad-web/dist/silero_vad_legacy.onnx \
  node_modules/@ricky0123/vad-web/dist/vad.worklet.bundle.min.js \
  "${OUTPUT_DIR}/${VAD_DIR}/"

cat > "${MANIFEST}" <<EOF
// Generated by scripts/build-stt-assets.sh — do not edit.
export const STT_WORKER_PATH = "${PUBLIC_BASE}/${WORKER_NAME}";
export const VAD_BUNDLE_PATH = "${PUBLIC_BASE}/${VAD_BUNDLE_NAME}";
export const ORT_WASM_BASE = "${PUBLIC_BASE}/${ORT_DIR}/";
export const VAD_ASSET_BASE = "${PUBLIC_BASE}/${VAD_DIR}/";
export const VAD_ORT_BASE = "${PUBLIC_BASE}/${VAD_ORT_DIR}/";
EOF

echo "==> Build complete!"
ls -la "${OUTPUT_DIR}"
echo "    ${MANIFEST}"
