# Shared helpers for the noise-suppression engine build scripts
# (build-*-worklet.sh). Sourced, not executed.
#
# Each engine ships as content-hashed files under public/javascripts/<engine>/
# plus a generated manifest module the loader imports. /plugins/ assets are
# served with long-lived immutable caching, so every rebuild must change the
# URLs — hence the hashes.

hash8() {
  sha256sum "$1" | cut -c1-8
}

# bundle_worklet <engine> <out_file>
bundle_worklet() {
  local engine="$1"
  local out="$2"
  cd "${PLUGIN_DIR}"
  pnpm install --silent
  pnpm exec esbuild "${PLUGIN_DIR}/src/${engine}-worklet/noise-suppression-processor.js" \
    --bundle --format=iife --minify --outfile="${out}"
}

# emit_ns_assets <engine> <worklet_bundle> <wasm_file> [model_file]
#
# Copies the artifacts into public/javascripts/<engine>/ with content-hashed
# names and regenerates assets/.../lib/resenha/ns-assets/<engine>.js.
emit_ns_assets() {
  local engine="$1"
  local bundle="$2"
  local wasm="$3"
  local model="${4:-}"

  local output_dir="${PLUGIN_DIR}/public/javascripts/${engine}"
  local manifest="${PLUGIN_DIR}/assets/javascripts/discourse/lib/resenha/ns-assets/${engine}.js"
  local public_base="/plugins/resenha/javascripts/${engine}"

  rm -rf "${output_dir}"
  mkdir -p "${output_dir}" "$(dirname "${manifest}")"

  local worklet_name="${engine}-worklet.$(hash8 "${bundle}").js"
  local wasm_name="${engine}.$(hash8 "${wasm}").wasm"
  install -m 644 "${bundle}" "${output_dir}/${worklet_name}"
  install -m 644 "${wasm}" "${output_dir}/${wasm_name}"

  {
    echo "// Generated by scripts/build-${engine}-worklet.sh — do not edit."
    echo "export const WORKLET_PATH = \"${public_base}/${worklet_name}\";"
    echo "export const WASM_PATH = \"${public_base}/${wasm_name}\";"
    if [ -n "${model}" ]; then
      local model_name="${engine}-model.$(hash8 "${model}").bin"
      install -m 644 "${model}" "${output_dir}/${model_name}"
      echo "export const MODEL_PATH = \"${public_base}/${model_name}\";"
    fi
  } > "${manifest}"

  echo "==> Build complete!"
  ls -la "${output_dir}"
  echo "    ${manifest}"
}
